const T={
  greet_m:{he:'בוקר טוב',en:'Good morning'},greet_a:{he:'צהריים טובים',en:'Good afternoon'},greet_e:{he:'ערב טוב',en:'Good evening'},
  gsub:{he:'הנה התמונה, בקצב שלכם — בלי לחץ.',en:'Here’s the picture, at your pace — no pressure.'},
  left_k:{he:'נשאר החודש — אחרי הוצאות וחיסכון',en:'left this month — after spending & saving'},
  days:{he:'יום {d} מאז המשכורת של {date}',en:'day {d} since your paycheck on {date}'},
  income:{he:'הכנסה',en:'Income'},spent:{he:'הוצאה',en:'Spent'},saved:{he:'חיסכון',en:'Saved'},
  si:{he:'נחסך והושקע',en:'Saved & invested'},si_s:{he:'כולל התלוש',en:'incl. payroll'},
  of_income:{he:'{p}% מההכנסה',en:'{p}% of income'},
  p_cycle:{he:'מהמשכורת',en:'Since paycheck'},p_30:{he:'30 ימים',en:'30 days'},p_90:{he:'3 חודשים',en:'3 months'},p_y:{he:'השנה',en:'This year'},
  spend_h:{he:'לאן זה הולך',en:'Where it goes'},
  goals_h:{he:'היעדים שלכם',en:'Your goals'},goals_s:{he:'הקישו על יעד לטיפ חכם',en:'tap a goal for a smart tip'},
  pay_h:{he:'סיפור התלוש',en:'The paycheck story'},pay_s:{he:'לאן הברוטו באמת הולך · {m}',en:'where the gross actually goes · {m}'},
  tax:{he:'מס',en:'Tax'},pension:{he:'פנסיה+השתלמות',en:'Pension+fund'},espp:{he:'ESPP',en:'ESPP'},net:{he:'נטו לבנק',en:'Net to bank'},
  gift:{he:'המעסיק מוסיף <b>{v}</b> מעל הברוטו — פנסיה, פיצויים וקרן השתלמות. מתנה אמיתית.',
        en:'Your employer adds <b>{v}</b> on top of gross — pension, severance & study fund. An actual gift.'},
  nw_s:{he:'שווי נקי · לחיצה על העין מסתירה',en:'net worth · tap the eye to hide'},
  nw_hint_on:{he:'הקישו על העין להצגה',en:'tap the eye to reveal'},
  nw_hint_off:{he:'{v}+ מאז נובמבר',en:'+{v} since November'},
  hz_d:{he:'יום־יום',en:'Day-to-day'},hz_m:{he:'5–10 שנים',en:'5–10 years'},hz_l:{he:'טווח ארוך',en:'Long-term'},
  recent_h:{he:'תנועות אחרונות',en:'Recent'},recent_s:{he:'היום־יום נשאר גלוי',en:'day-to-day stays visible'},
  as_of:{he:'נכון ל־',en:'as of '},
  v_me:{he:'אני',en:'Me'},v_couple:{he:'זוגי',en:'Couple'},
  cp_hero_k:{he:'ביחד — רק מה שכל אחד בחר לשתף',en:'together — only what you each chose to share'},
  cp_together:{he:'ביחד',en:'Together'},cp_you:{he:'את/ה',en:'You'},cp_partner:{he:'בן/בת הזוג',en:'Partner'},
  cp_s:{he:'מה ששניכם רואים — הפרטי נשאר פרטי',en:'what you both see — private stays private'},
  cp_demo:{he:'דמו: כך ייראה החיבור הזוגי. נתוני בן/בת הזוג מדומים.',en:'Demo: how pairing will look. Partner data is simulated.'},
  cp_holds:{he:'מה שותף מכל צד',en:'What each side shares'},
  cp_spend_h:{he:'הוצאות משותפות',en:'Shared spending'},
  cp_spend_s:{he:'החודש · שני הצדדים יחד',en:'this month · both sides combined'},
  cp_goal_h:{he:'יעד משותף',en:'Shared goal'},
  cp_goal_s:{he:'שניכם מפקידים אליו',en:'you both put into it'},
  cp_goal_name:{he:'טיול איטליה',en:'Italy trip'},
  pg_h:{he:'משחק החזרזיר',en:'The piggy game'},
  pg_sub:{he:'מה אם? שחקו רגע — בלי מחויבות ובלי שיפוטיות',en:'what if? play for a second — no strings, no judgement'},
  pg_cat:{he:'אם נצמצם קצת ב…',en:'If we trim a little on…'},
  pg_cut:{he:'בכמה לצמצם',en:'Trim by'},
  pg_years:{he:'לכמה שנים',en:'For how many years'},
  pg_yr_u:{he:'שנים',en:'years'},
  pg_monthly:{he:'≈ {m} מתפנים כל חודש',en:'≈ {m} freed up monthly'},
  pg_fv_k:{he:'שווה בעוד {y} שנים, אם מושקע',en:'worth in {y} years, if invested'},
  pg_note:{he:'הנחה: תשואה שנתית 4%, ריבית דריבית. עובדה להשוואה — לא עצה.',en:'Assumes a 4% yearly return, compounding. A fact to compare — not advice.'},
  cm_total:{he:'סה״כ {v} · {n} תנועות',en:'{v} total · {n} transactions'},
  cm_none:{he:'אין תנועות בקטגוריה הזו בתקופה.',en:'No transactions here for this period.'},
  tip_done:{he:'היעד הושלם.',en:'Goal reached.'},
  tip_ontrack:{he:'אתם בכיוון: הפער נסגר עם <b>~{need}</b> בחודש — פחות מקצב החיסכון הנוכחי שלכם ({pace}). ממשיכים ככה — מגיעים עד {date}.',en:'You’re on track: <b>~{need}</b>/month closes the gap — less than your current saving pace ({pace}). Keep going and you’re there by {date}.'},
  tip_trim:{he:'כדי להגיע בזמן צריך <b>~{need}</b> בחודש. אפשרות אחת: {parts}.',en:'Getting there on time needs <b>~{need}</b>/month. One option: {parts}.'},
  tip_nodate:{he:'בקצב הנוכחי ({pace} בחודש) תגיעו בעוד כ־<b>{m} חודשים</b>. רוצים מוקדם? הוסיפו תאריך יעד ונחשב יחד.',en:'At your current pace ({pace}/month) you’ll get there in about <b>{m} months</b>. Want it sooner? Add a target date and we’ll do the math.'},
  tip_hard:{he:'הפער דורש <b>~{need}</b> בחודש — יותר מהקצב הנוכחי. אפשר לפרוס את התאריך, או לשחק במשחק החזרזיר למטה.',en:'This needs <b>~{need}</b>/month — more than the current pace. You could stretch the date, or play the piggy game below.'},
  cp_tip:{he:'אם עמית יפקידו <b>{a}</b> בחודש וגיא <b>{b}</b> — תגיעו ליעד בעוד כ־<b>{m} חודשים</b>.',en:'If Amit puts in <b>{a}</b>/month and Guy <b>{b}</b> — you’ll reach the goal in about <b>{m} months</b>.'},
  cp_goal_hint:{he:'הקישו לטיפ',en:'tap for a tip'},
  cat:{housing:{he:'דיור',en:'Housing'},groceries:{he:'סופר',en:'Groceries'},dining:{he:'מסעדות',en:'Dining'},
    shopping:{he:'קניות',en:'Shopping'},health:{he:'בריאות',en:'Health'},transport:{he:'תחבורה',en:'Transport'},
    utilities:{he:'חשבונות',en:'Utilities'},entertainment:{he:'בילויים',en:'Entertainment'},
    investment:{he:'השקעות',en:'Investment'},income:{he:'הכנסה',en:'Income'},transfer:{he:'העברה',en:'Transfer'},other:{he:'אחר',en:'Other'}},
};